import { CalendarOutlined, UnorderedListOutlined } from '@ant-design/icons';
import { Card, Tabs, Tag } from 'antd';
import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import CandidateCard from '../components/CandidateCard';
import PipelineKanban from '../components/PipelineKanban';
import { statusText } from '../constants/enums';
import { api } from '../utils/api';
export default function JobDetailPage(){ const {id}=useParams(); const [job,setJob]=useState<Job>(); const [resumes,setResumes]=useState<Resume[]>([]); const [interviews,setInterviews]=useState<Interview[]>([]); const load=async()=>{const [j,r,i]=await Promise.all([api.get(`/jobs/${id}`),api.get(`/jobs/${id}/resumes`),api.get(`/jobs/${id}/interviews`)]); setJob(j.data); setResumes(r.data); setInterviews(i.data)}; useEffect(()=>{load()},[id]); return <><h1 className="page-title">{job?.title}</h1><Card className="tf-card" style={{margin:'18px 0'}}><Tag color="green">{job&&statusText[job.status]}</Tag> {job?.department} · {job?.location} · {job?.salaryRange}<p>{job?.description}</p><p className="subtle">{job?.requirements}</p></Card><Tabs items={[{key:'candidates',label:<><UnorderedListOutlined/>候选人列表</>,children:<div style={{display:'grid',gap:12}}>{resumes.map(r=>r.candidate&&<CandidateCard key={r.id} candidate={{...r.candidate,resumes:[r]}}/> )}</div>},{key:'kanban',label:'PipelineKanban 看板',children:<PipelineKanban resumes={resumes} onMove={async(rid,status)=>{await api.patch(`/resumes/${rid}/status`,{status,reason:'看板拖拽'});load();}}/>},{key:'calendar',label:<><CalendarOutlined/>面试日历</>,children:<div style={{display:'grid',gap:10}}>{interviews.map(i=><Card key={i.id} size="small">{i.resume?.candidate?.name} · 第 {i.round} 轮 · {new Date(i.scheduledAt).toLocaleString()} · {statusText[i.result]}</Card>)}</div>}]} /></>; }
